{"uuid": "fd78127e-f176-40e4-89e2-dde930322def", "children": ["cfc3f23e-fdd4-4f3e-8814-92cd32a41aef", "25bda764-aef0-4529-ab3d-22e719b03a51", "646b3a96-c560-41cc-94fc-eb82305879f9", "8733b11b-9656-4cee-b711-6512c4e06211", "7498a97f-ec80-4896-95e3-fae86a94c7e0"], "befores": [{"name": "setup", "status": "passed", "start": 1610290287957, "stop": 1610290297142}], "afters": [{"name": "setup::0", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: chrome not reachable\n  (Session info: chrome=87.0.4280.88)\n\n", "trace": "  File \"c:\\users\\indrasen\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\allure_commons\\_allure.py\", line 185, in __call__\n    return self._fixture_function(*args, **kwargs)\n  File \"c:\\users\\indrasen\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\_pytest\\fixtures.py\", line 926, in _teardown_yield_fixture\n    next(it)\n  File \"C:\\Users\\indrasen\\PycharmProjects\\pythonProject1\\Assignment\\tests\\conftest.py\", line 30, in setup\n    driver.close()\n  File \"c:\\users\\indrasen\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 688, in close\n    self.execute(Command.CLOSE)\n  File \"c:\\users\\indrasen\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 321, in execute\n    self.error_handler.check_response(response)\n  File \"c:\\users\\indrasen\\appdata\\local\\programs\\python\\python39\\lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 242, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1610290356209, "stop": 1610290356412}], "start": 1610290287957, "stop": 1610290356412}